name: CI Build
on:
 push:
   branches:
     - 'main'
jobs:
 build:
   name: Maven Build
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Setup Java 17
       uses: actions/setup-java@v3
       with:
         java-version: 17
         distribution: 'temurin'
         cache: 'maven'
     - name: Setup Testcontainers Cloud Client
       uses: atomicjar/testcontainers-cloud-setup-action@v1
       with:
         token: ${{ secrets.aj_tcc_svc_YVzGTuDO5cjf7-eKXaxiUJJadFUSK3meJfPyW1u9nFcK4 }}
     - name: Build with Maven
       run: ./mvnw verify
